name: surf_flutter_summer_school_24
description: "Surf Flutter Summer School '24"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  collection: ^1.18.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter:
  assets:
    - assets/images/
  uses-material-design: true


fonts:
  - family: Roboto
  - asset:  -assets/fonts/Roboto-Black.ttf
  - asset:  -assets/fonts/Roboto-BlackItalic.ttf
  - asset:  -assets/fonts/Roboto-Bold.ttf
  - asset:  -assets/fonts/Roboto-BoldItalic.ttf
  - asset:  -assets/fonts/Roboto-Italic.ttf
  - asset:  -assets/fonts/Roboto-Light.ttf
  - asset:  -assets/fonts/Roboto-LightItalic.ttf
  - asset:  -assets/fonts/Roboto-Medium.ttf
  - asset:  -assets/fonts/Roboto-MediumItalic.ttf
  - asset:  -assets/fonts/Roboto-Regular.ttf
  - asset:  -assets/fonts/Roboto-Thin.ttf
  - asset:  -assets/fonts/Roboto-ThinItalic.ttf
